title: "Chris Stroud | BizOps, RevOps, and Analytics"
description: "Chris Stroud - Director of Business Operations specializing in BizOps, RevOps, and Analytics"
logo: /assets/img/profile.jpg
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
