title: "Chris Stroud"
tagline: "BizOps, RevOps, and Analytics"
description: "Director of Business Operations specializing in BizOps, RevOps, and Analytics"
logo: /assets/img/profile.jpg
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
